# Generated by Django 4.0.6 on 2022-07-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Welcome text'),
        ),
    ]
