# Generated by Django 4.0.6 on 2022-07-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizengo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
