# Generated by Django 4.0.6 on 2022-07-26 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizengo', '0002_alter_creator_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='body',
        ),
    ]
