# Generated by Django 4.0.6 on 2022-07-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizengo', '0003_remove_creator_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='topic',
            field=models.CharField(choices=[('Life', 'LF'), ('Family', 'FM'), ('Politics', 'PT'), ('Solidarity', 'SD'), ('Education', 'ED'), ('Other', 'OT')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Topics',
        ),
    ]
