# Generated by Django 4.0.6 on 2022-07-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizengo', '0004_alter_petition_topic_delete_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='image',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
