# Generated by Django 4.0.6 on 2022-07-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizengo', '0006_alter_petition_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
    ]
